package com.trash2money.trashapp.KClasses

class CouponItem(
    var id: String,
    var img: String,
    var brand: String,
    var category: String,
    var cost: Float,
    var description: String,
    var disc: String,
    var qty: Int,
    var rating: Float,
    var validate: String,
    var full_desc: String,
    val value: Double,
    var views: Int,
    var impressions: Int,
    var status: String,
    val idkey: String,
    var prio: Double,
    var rules: String,
    var how: String,
    var codcoupon: String,
    var coupontrash: Boolean,
    var marca: String,
    val ratingprice: Int
) {
    constructor() : this("",
        "",
        "",
        "",
        0F,
        "",
        "",
        0,
        0F,
        "",
        "",
        0.0,
        0,
        0,
        "",
        "",
        0.0,
        "",
        "",
        "",
        true,
        "",
        0)

}